pipeline{
    agent any
    stages{
        stage("compile"){
			steps{
				sh 'java --version'
			}            
        }
//        stage("run"){
//            steps{
//				bat 'java Test'
//			}
//        }
    }
}