pipeline{
    agent any
    stages{
        stage("compile"){
			steps{ // D:\kishan.k\CICD\com.learning.cicd.pipeline\src\main\java\com\learning\cicd\pipeline\creating\pipeline
				bat 'javac src\\main\\java\\com\\learning\\cicd\\pipeline\\creating\\pipeline\\Test.java'
			}            
        }
        stage("run"){
            steps{
				bat 'java -cp src\\main\\java com.learning.cicd.pipeline.creating.pipeline.Test'
			}
        }
    }
    
    // this post will work only after completing all the stage in stages
    post{
		always{
			bat 'echo "KISHAN MAHESH KUSHWAHA ALWAYS"'
		}
		
		success{
			bat 'echo "KISHAN MAHESH KUSHWAHA SUCCESS"'
		}
	} 
}